services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: picpay_simplificado
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: nest_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/picpay_simplificado"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["npm", "run", "start:dev"]

volumes:
  pgdata:
